/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package huruf.hijaiyah;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Habsyi Ikhlashul A
 */
public class Pilihan5 extends javax.swing.JFrame {

    /**
     * Creates new form Pilihan5
     */
    public Pilihan5() {
        initComponents();
         setLocationRelativeTo(null);
        //setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         K5.requestFocus();
        K6.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        K3 = new javax.swing.JButton();
        K2 = new javax.swing.JButton();
        K1 = new javax.swing.JButton();
        K4 = new javax.swing.JButton();
        K5 = new javax.swing.JButton();
        K6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        K3.setText("Jilid 3");
        K3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K3ActionPerformed(evt);
            }
        });
        getContentPane().add(K3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 70, -1));

        K2.setText("Jilid 2");
        K2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K2ActionPerformed(evt);
            }
        });
        getContentPane().add(K2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 70, -1));

        K1.setText("Jilid 1");
        K1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K1ActionPerformed(evt);
            }
        });
        getContentPane().add(K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, -1));

        K4.setText("Jilid 4");
        K4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K4ActionPerformed(evt);
            }
        });
        getContentPane().add(K4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 71, -1));

        K5.setText("Jilid 5");
        K5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                K5ActionPerformed(evt);
            }
        });
        getContentPane().add(K5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 69, -1));

        K6.setText("Jilid 6");
        K6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(K6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 70, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Pilih Kode Yang Akan DiMainkan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void K1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K1ActionPerformed
        // TODO add your handling code here:
        Soa1Part1 p1 = new Soa1Part1();
        p1.setVisible(true);
        this.dispose();
        K2.setEnabled(true);
    }//GEN-LAST:event_K1ActionPerformed

    private void K5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Kita Masuk Tahap Tebak macam-macam nama buah","", JOptionPane.ERROR_MESSAGE, new ImageIcon ("src/file/buah.png"));
         String siap = JOptionPane.showInputDialog(null, "Apakah Anda siap","",JOptionPane.QUESTION_MESSAGE);
            if (siap.equals("SIAP")|siap.equals("siap")|siap.equals("iya")) {
            }else {
               JOptionPane.showMessageDialog(null, "Beneran anda tidak mau menjawab pertanyaan kami"," ", JOptionPane.INFORMATION_MESSAGE, new ImageIcon ("src/file/takon.png"));  
            }
        Soal5Part1 p4 = new Soal5Part1();
         p4.setVisible(true);
        this.dispose();
        K4.requestFocus();
    }//GEN-LAST:event_K5ActionPerformed

    private void K2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K2ActionPerformed
        // TODO add your handling code here:
        Soal2Part1 p2 = new Soal2Part1();
         p2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_K2ActionPerformed

    private void K3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K3ActionPerformed
        // TODO add your handling code here:
        Soal3 p3 = new Soal3();
         p3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_K3ActionPerformed

    private void K4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_K4ActionPerformed
        // TODO add your handling code here:
        Soal4 p4 = new Soal4();
         p4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_K4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuUtama Mu= new MenuUtama();
        Mu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int a= JOptionPane.showConfirmDialog(this,"Anda Yakin Mau Keluar Dari Aplikasi");
        if(a == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pilihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pilihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pilihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pilihan5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pilihan5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton K1;
    private javax.swing.JButton K2;
    private javax.swing.JButton K3;
    private javax.swing.JButton K4;
    private javax.swing.JButton K5;
    private javax.swing.JButton K6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
